"use client";
import {useEffect,useState} from "react";
import {onAuthStateChanged,signOut} from "firebase/auth";
import {collection,doc,getDoc,getDocs,query,where} from "firebase/firestore";
import {getFirebaseAuth,getFirebaseDb} from "@/lib/firebase";
export default function StudentPortal(){
 const [u,setU]=useState<any>(null),[p,setP]=useState<any>({}),[courses,setCourses]=useState<any[]>([]),[marks,setMarks]=useState<any[]>([]),[att,setAtt]=useState<any[]>([]),[msg,setMsg]=useState("");
 async function load(uid:string){try{const db=getFirebaseDb(),ps=await getDoc(doc(db,"profiles",uid));if(!ps.exists()){setMsg("Profile not found.");return}setP(ps.data());const en=await getDocs(query(collection(db,"enrollments"),where("studentId","==",uid)));const cs=await Promise.all(en.docs.map(async e=>{const c=await getDoc(doc(db,"courses",String(e.data().courseId)));return c.exists()?{id:c.id,...c.data()}:null}));setCourses(cs.filter(Boolean));const m=await getDocs(query(collection(db,"marks"),where("studentId","==",uid)));setMarks(m.docs.map(d=>({id:d.id,...d.data()})));const a=await getDocs(query(collection(db,"attendanceRecords"),where("studentId","==",uid)));setAtt(a.docs.map(d=>d.data()))}catch(e){setMsg(e instanceof Error?e.message:"Could not load records")}}
 useEffect(()=>onAuthStateChanged(getFirebaseAuth(),x=>{if(!x){location.replace("/login");return}setU(x);load(x.uid)}),[]);
 if(!u)return <main className="page"><div className="loading">Loading dashboard…</div></main>;
 const present=att.filter(x=>["present","late","excused"].includes(x.status)).length;const pct=att.length?Math.round(present/att.length*100):null;
 return <main className="page"><nav className="nav"><div className="brand"><div className="logo">A</div><div>ASRS<small>Student Portal</small></div></div><div className="nav-actions"><span className="navtag">{u.email}</span><button className="button small" onClick={()=>signOut(getFirebaseAuth())}>Sign out</button></div></nav><section className="dashboard"><div className="dash-head"><div><span className="eyebrow">Student workspace</span><h1>Welcome, {p.fullName||"Student"}.</h1><p>{p.rollNo||"No roll number"} • {p.department||"Department"} • {u.email}</p></div></div>{msg&&<div className="status">{msg}</div>}<div className="metric-grid"><div className="metric"><b>{pct===null?"—":pct+"%"}</b><span>Attendance</span></div><div className="metric"><b>{courses.length}</b><span>Enrolled courses</span></div><div className="metric"><b>{marks.length}</b><span>Published marks</span></div><div className="metric"><b>Student</b><span>Account role</span></div></div><div className="dashboard-grid"><section className="panel"><div className="section-title"><span>My courses</span><small>Live Firestore records</small></div>{courses.length?<div className="list">{courses.map(c=><div className="list-row" key={c.id}><div><b>{c.courseCode||"Course"}</b><span>{c.courseName||"Untitled"}</span></div><em>{c.semester||"Current"}</em></div>)}</div>:<div className="empty">No courses assigned yet.</div>}</section><section className="panel"><div className="section-title"><span>Marks</span><small>Latest academic records</small></div>{marks.length?<div className="list">{marks.slice(0,8).map(m=><div className="list-row" key={m.id}><div><b>{m.assessment||"Assessment"}</b><span>{m.courseId||"Course"}</span></div><strong>{m.score??0}/{m.maxScore??0}</strong></div>)}</div>:<div className="empty">No marks published yet.</div>}</section></div></section></main>
}