"use client";
import {useEffect,useState} from "react";
import {onAuthStateChanged,signOut} from "firebase/auth";
import {addDoc,collection,doc,getDoc,getDocs,query,serverTimestamp,setDoc,where} from "firebase/firestore";
import {getFirebaseAuth,getFirebaseDb} from "@/lib/firebase";
export default function FacultyPortal(){
 const [u,setU]=useState<any>(null),[courses,setCourses]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[cid,setCid]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[state,setState]=useState<any>({}),[msg,setMsg]=useState("");
 async function load(uid:string){const db=getFirebaseDb();const p=await getDoc(doc(db,"profiles",uid));if(!p.exists()||!["faculty","admin"].includes(p.data().role)){location.replace("/student");return}const s=await getDocs(query(collection(db,"courses"),where("instructorId","==",uid)));const cs=s.docs.map(d=>({id:d.id,...d.data()}));setCourses(cs);if(cs[0])loadStudents(cs[0].id)}
 async function loadStudents(id:string){setCid(id);const en=await getDocs(query(collection(getFirebaseDb(),"enrollments"),where("courseId","==",id)));const ps=await Promise.all(en.docs.map(async e=>{const p=await getDoc(doc(getFirebaseDb(),"profiles",String(e.data().studentId)));return p.exists()?{id:p.id,...p.data()}:null}));setStudents(ps.filter(Boolean))}
 useEffect(()=>onAuthStateChanged(getFirebaseAuth(),x=>{if(!x){location.replace("/login");return}setU(x);load(x.uid)}),[]);
 async function save(){if(!cid||!students.length){setMsg("Select a course with enrolled students.");return}try{const db=getFirebaseDb(),s=await addDoc(collection(db,"attendanceSessions"),{courseId:cid,sessionDate:date,createdBy:u.uid,createdAt:serverTimestamp()});await Promise.all(students.map(x=>setDoc(doc(collection(db,"attendanceRecords")),{sessionId:s.id,studentId:x.id,status:state[x.id]||"present",markedAt:serverTimestamp()})));setMsg("Attendance saved.");setState({})}catch(e){setMsg(e instanceof Error?e.message:"Save failed")}}
 if(!u)return <main className="page"><div className="loading">Loading faculty workspace…</div></main>;
 return <main className="page"><nav className="nav"><div className="brand"><div className="logo">A</div><div>ASRS<small>Faculty Portal</small></div></div><div className="nav-actions"><button className="button small" onClick={()=>signOut(getFirebaseAuth())}>Sign out</button></div></nav><section className="dashboard"><div className="dash-head"><div><span className="eyebrow">Faculty workspace</span><h1>Mark attendance.</h1><p>Attendance is written directly to Firestore.</p></div></div>{msg&&<div className="status">{msg}</div>}<section className="panel"><div className="form-row"><label>Course<select value={cid} onChange={e=>loadStudents(e.target.value)}>{courses.length?courses.map(c=><option key={c.id} value={c.id}>{c.courseCode} — {c.courseName}</option>):<option>No assigned courses</option>}</select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><div className="section-title" style={{marginTop:25}}><div><span>{students.length} students</span><small>Set status and save one attendance session.</small></div><button className="button primary" onClick={save}>Save attendance</button></div>{students.length?<div className="list">{students.map(s=><div className="list-row" key={s.id}><div><b>{s.fullName||"Student"}</b><span>{s.rollNo||s.id}</span></div><select value={state[s.id]||"present"} onChange={e=>setState({...state,[s.id]:e.target.value})}><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option><option value="excused">Excused</option></select></div>)}</div>:<div className="empty">Assign this faculty as instructorId on a course, then enroll students.</div>}</section></section></main>
}