"use client";
import Link from "next/link";
import {FormEvent,useState} from "react";
import {createUserWithEmailAndPassword} from "firebase/auth";
import {doc,setDoc,serverTimestamp} from "firebase/firestore";
import {getFirebaseAuth,getFirebaseDb} from "@/lib/firebase";
export default function Register(){
 const [name,setName]=useState(""),[roll,setRoll]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[dept,setDept]=useState("CSE"),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMsg("Creating account…");try{const u=await createUserWithEmailAndPassword(getFirebaseAuth(),email.trim(),password);await setDoc(doc(getFirebaseDb(),"profiles",u.user.uid),{fullName:name.trim(),rollNo:roll.trim(),department:dept,role:"student",createdAt:serverTimestamp()});location.replace("/student")}catch(x){setMsg(x instanceof Error?x.message:"Could not create account");setBusy(false)}}
 return <main className="page"><nav className="nav"><Link href="/" className="brand" style={{color:"inherit",textDecoration:"none"}}><div className="logo">A</div><div>ASRS<small>Student registration</small></div></Link><Link href="/login" className="button">Sign in</Link></nav><section className="auth-shell"><div className="auth-card"><span className="eyebrow">New student</span><h1>Create account.</h1><p>Registration creates a Student account and profile in Firebase.</p><form onSubmit={submit}><label>Full name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Roll number<input value={roll} onChange={e=>setRoll(e.target.value)} required/></label><label>Department<select value={dept} onChange={e=>setDept(e.target.value)}><option>CSE</option><option>ECE</option><option>EE</option><option>ME</option><option>Other</option></select></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="button primary wide" disabled={busy}>{busy?"Creating…":"Create account"}</button></form>{msg&&<div className="status">{msg}</div>}</div></section></main>
}